CREATE TABLE learning_context_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(200) NOT NULL,
    project_id VARCHAR(128) NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    event_type VARCHAR(64) NOT NULL
        CHECK (event_type IN ('REVISION_RECORDED','REVIEW_RECORDED','RATING_RECORDED')),
    event_key VARCHAR(256) NOT NULL,
    payload_json TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING','PROCESSING','DONE','FAILED')),
    attempts INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(event_type, event_key)
);
CREATE INDEX learning_context_outbox_claim_idx
    ON learning_context_outbox(status, next_attempt_at, created_at);

CREATE TABLE learning_context_applied_events (
    outbox_id BIGINT PRIMARY KEY REFERENCES learning_context_outbox(id) ON DELETE CASCADE,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE project_context_projection (
    project_id VARCHAR(128) PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,
    user_id VARCHAR(200) NOT NULL,
    unresolved_feedback_json TEXT NOT NULL DEFAULT '[]',
    covered_outcomes_json TEXT NOT NULL DEFAULT '[]',
    latest_revision_id VARCHAR(128),
    latest_review_id VARCHAR(128),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX project_context_owner_idx ON project_context_projection(user_id, updated_at DESC);

CREATE TABLE learner_concept_state (
    user_id VARCHAR(200) NOT NULL,
    concept_key VARCHAR(200) NOT NULL,
    misconception_summary TEXT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL CHECK (confidence BETWEEN 0.0 AND 1.0),
    occurrence_count INT NOT NULL DEFAULT 1,
    provenance_revision_id VARCHAR(128) NOT NULL,
    provenance_review_id VARCHAR(128) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY(user_id, concept_key)
);
CREATE INDEX learner_concept_state_recall_idx
    ON learner_concept_state(user_id, updated_at DESC);

CREATE TABLE authoring_behavior_profile (
    user_id VARCHAR(200) PRIMARY KEY,
    recurring_patterns_json TEXT NOT NULL DEFAULT '{}',
    feedback_preference VARCHAR(128) NOT NULL DEFAULT '',
    feedback_actionability_score DOUBLE PRECISION
        CHECK (feedback_actionability_score BETWEEN 1.0 AND 5.0),
    evidence_practice_score DOUBLE PRECISION,
    revision_count INT NOT NULL DEFAULT 0,
    review_count INT NOT NULL DEFAULT 0,
    rating_count INT NOT NULL DEFAULT 0,
    provenance_revision_id VARCHAR(128),
    provenance_review_id VARCHAR(128),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
